add sysId example
robotpy/examples pull request #111
Opened 2024-01-18 12:48 UTC by LucienMorey

Currently a WIP...

Outstanding tasks:

- [ ] Finish Port of robot.py
- [ ] confirm sysid log function is correct
- [ ] convert docs strings
- [ ] run on robot

2024-01-21 04:23 UTC, LucienMorey commented
I don't have a tank drive handy to test this properly but I did adapt it for my team's swerve drive and deploy it there. feel free to request changes but I think this is good to go as a baseline

2024-01-27 05:01 UTC, auscompgeek commented
Please add the robot to the test list.

2024-01-27 05:54 UTC, auscompgeek commented on SysId/subsystems/drive.py
> +    def arcadeDriveCommand(self, fwd: float, rot: float) -> Command:
This should take lambdas, see https://github.com/wpilibsuite/allwpilib/blob/84ef71ace0648a71bd6e60e16c38be75914bb59d/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/subsystems/Drive.java#L118-L122

2024-03-10 03:02 UTC, auscompgeek requested changes

2024-03-10 03:02 UTC, auscompgeek commented on SysId/sysidroutinebot.py
> +                lambda: self.controller.getLeftY(), lambda: self.controller.getRightX()
The signs should match the upstream example.
```suggestion
                lambda: -self.controller.getLeftY(), lambda: -self.controller.getRightX()
```

2024-03-10 03:02 UTC, auscompgeek commented on SysId/subsystems/drive.py
> +        # self.right_motor.addFollower(PWMSparkMax(DriveConstants.kRightMotor2Port))
`addFollower` is fixed.
```suggestion
        self.left_motor.addFollower(PWMSparkMax(DriveConstants.kLeftMotor2Port))

        # The motors on the right side of the drive
        self.right_motor = PWMSparkMax(DriveConstants.kRightMotor1Port)
        self.right_motor.addFollower(PWMSparkMax(DriveConstants.kRightMotor2Port))
```

2024-03-10 03:42 UTC, auscompgeek approved these changes
LGTM, thanks!

2024-03-10 03:42 UTC, merged