Added relay example.
robotpy/examples pull request #80
Opened 2023-12-02 15:35 UTC by mbardoeChoate

I haven't added code to another person's repository before, so I am trying to start small. I saw the request for more examples and tried to pick the easiest thing I could. Probably not a super helpful example, but if I can do this well, I will try to pick off more important stuff later.

2023-12-02 20:04 UTC, virtuald requested changes
Mostly looks good, thanks! Just a few comment related adjustments, see https://github.com/robotpy/examples/blob/main/CONTRIBUTING.md#include-all-the-comments and the rest of that doc. 

Thanks!

2023-12-02 20:04 UTC, virtuald commented on relay/robot.py
> +        if forward and reverse:
We try to keep the original comments found in the Java example, please add them:

* https://github.com/wpilibsuite/allwpilib/blob/96914143ba554cf2644229ddf54d1f4bead0a654/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/relay/Robot.java#L27
* https://github.com/wpilibsuite/allwpilib/blob/96914143ba554cf2644229ddf54d1f4bead0a654/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/relay/Robot.java#L34
* etc

2023-12-02 20:04 UTC, virtuald commented on relay/robot.py
> +        """
This comment isn't present in the original example, so let's omit it.

2023-12-02 23:27 UTC, mbardoeChoate commented
Tried to fix the comments. Thanks for the quick feedback.

2023-12-03 00:20 UTC, auscompgeek commented on relay/robot.py
> +        self.joystick = wpilib.Joystick(self.joystickChannel)
The Java/C++ example doesn't define a separate variable for the joystick channel number; let's avoid introducing one here.
```suggestion
        self.joystick = wpilib.Joystick(0)
```

2023-12-03 06:31 UTC, merged

2023-12-03 06:31 UTC, virtuald commented
Thanks!