Add mecanum-bot example
robotpy/examples pull request #92
Opened 2023-12-07 07:30 UTC by fletch3555

wpimath.kinematics.ChassisSpeeds.descretize(...) doesn't seem to exist.  Am I missing it somewhere? Is it new and needs to be added? Is there a different/better approach?

RobotPy docs: https://robotpy.readthedocs.io/projects/wpimath/en/latest/wpimath.kinematics/ChassisSpeeds.html
wpilibj source: https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java#L92

2023-12-08 02:18 UTC, fletch3555 commented
> It was added in the beta, and the docs were not updated yet. The doc site has moved, and you can see that function here: https://robotpy.readthedocs.io/projects/robotpy/en/latest/wpimath.kinematics/ChassisSpeeds.html#wpimath.kinematics.ChassisSpeeds.discretize

Good call.  I didn't realize I wasn't running the 2024 beta version.  Should be updated now

2023-12-18 03:12 UTC, virtuald requested changes
If you rebase on main and add the copyright statement I think we're good here.

2023-12-18 03:12 UTC, virtuald commented on mecanum-bot/drivetrain.py
> +    # TRACK_WIDTH = 0.381 * 2  # meters
Why are these comments here?

2023-12-18 05:18 UTC, fletch3555 commented on mecanum-bot/drivetrain.py
> +    # TRACK_WIDTH = 0.381 * 2  # meters
Just copy/paste... They're gone now.

2023-12-19 09:32 UTC, merged